package controller;

public class Parameters {
    public static final String ERROR = "errorMessage";
    public static final String LOGIN = "login";
    public static final String PASSWORD = "password";
    public static final String USER_ID = "userId";
    public static final String ROLE = "role";
    public static final String PRODUCTS = "products";
    public static final String PRODUCT_PROPERTIES = "productProperties";
    public static final String PRODUCT_ID = "productId";
    public static final String PRODUCT_NAME = "name";
    public static final String ORDERS = "orders";
    public static final String ORDER_ID = "orderId";
    public static final String ORDER_STATUS = "orderStatus";
    public static final String USERS = "users";
    public static final String NEW_BLOCK_STATUS = "newBlockStatus";
    public static final String CART_USER_ID = "cartUserId";
    public static final String BLOCKED = "blocked";
    public static final String LOCALE = "locale";
    public static final String USERNAME_EN = "usernameEn";
    public static final String USERNAME = "username";
    public static final String USERNAME_UK = "usernameUk";
    public static final String PROD_NAME_EN = "prodNameEn";
    public static final String PROD_NAME_UK = "prodNameUk";
    public static final String PRICE = "price";
    public static final String PROPERTY_NAMES_EN = "propertyNamesEn";
    public static final String PROPERTY_NAMES_UK = "propertyNamesUk";
    public static final String PROPERTY_VALUES_EN = "propertyValuesEn";
    public static final String PROPERTY_VALUES_UK = "propertyValuesUk";
    public static final String LOCALE_EN = "en";
    public static final String LOCALE_UK = "uk";
    public static final String SORT_OPTION = "sortOption";
    public static final String SORT_BY_NAME_AZ = "byNameAZ";
    public static final String SORT_BY_NAME_ZA = "byNameZA";
    public static final String SORT_PRICE_HIGH_LOW = "priceHighLow";
    public static final String SORT_PRICE_LOW_HIGH = "priceLowHigh";
    public static final String SORT_NEWEST = "newest";
    public static final String PRODUCT_CREATION_DATE = "creationDate";
    public static final String PAGE = "page";
    public static final int RECORDS_PER_PAGE = 10;
    public static final String PRICE_FROM = "priceFrom";
    public static final String PRICE_TO = "priceTo";
    public static final String SELECTED_PROPERTIES = "selectedProperties";
    public static final String ACTION = "action";
}
